generalTab=Pallet calculation
palletPropertyId=Property ID "Pallet relevant"
orderPropertyTypeId=Order property type ID "Pallet count"
quantityPerPallet=Units per pallet
maxPalletWeight=Maximum pallet weight (kg)
