generalTab=Palettenberechnung
palletPropertyId=Eigenschafts-ID "Palettenrelevant"
orderPropertyTypeId=Auftragseigenschafts-ID "Palettenanzahl"
quantityPerPallet=Stück pro Palette
maxPalletWeight=Maximalgewicht der Palette (kg)
